language: generic 
sudo: required
services:
  - docker

before_install:
  - docker build -t ronysetyawanst/docker-telkom-app -f Dockerfile.dev .

script:
  - docker run -e CI=true ronysetyawanst/docker-telkom-app npm run test

deploy:
  provider: elasticbeanstalk
  region: "ap-southeast-1"
  app: "docker-telkom-app"
  env: "Dockertelkomapp-env"
  bucket_name: "elasticbeanstalk-ap-southeast-1-632537985342"
  bucket_path: "docker-telkom-app"
  on:
    branch: master
  access_key_id: "$AWS_ACCESS_KEY"
  secret_access_key:
    secure: "$AWS_SECRET_KEY"
